name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.4

flutter:

  uses-material-design: true
